# Generated by Django 6.0.2 on 2026-02-28 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('par_level', models.IntegerField(default=0)),
                ('products', models.ManyToManyField(blank=True, related_name='categories', to='database.product')),
            ],
        ),
        migrations.CreateModel(
            name='DistributionCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('allocation', models.IntegerField(default=0)),
                ('shops', models.ManyToManyField(blank=True, related_name='distribution_centers', to='database.shop')),
            ],
        ),
        migrations.CreateModel(
            name='TierThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xs_thresh', models.IntegerField(default=4)),
                ('s_thresh', models.IntegerField(default=4)),
                ('m_thresh', models.IntegerField(default=4)),
                ('l_thresh', models.IntegerField(default=2)),
                ('xl_thresh', models.IntegerField(default=2)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='database.shop')),
            ],
        ),
        migrations.CreateModel(
            name='DCInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dc_inventory', to='database.product')),
                ('dc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='database.distributioncenter')),
            ],
            options={
                'unique_together': {('dc', 'product')},
            },
        ),
    ]
