# Generated by Django 6.0.2 on 2026-02-28 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_product_category_category_distributioncenter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tierthreshold',
            name='shop',
        ),
    ]
